import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[font]
size = 12
offset ={ x= 0, y = -1 }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[window]
dynamic_padding = true
decorations = "Full"
padding ={ x = 0, y = 0 }

[env]
TERM = "xterm-256color"

# [keyboard]
# bindings = [
#   { key = "Right", mods = "Control", chars = "\u001BF" }, # Jump word right
#   { key = "Left",  mods = "Control", chars = "\u001BB" }, # Jump word left
#   { key = "Left", mods = "Control|Super", chars = "\u001bOH", mode = "AppCursor" }, # Goto ^
#   { key = "Right", mods= "Control|Super", chars= "\u001bOF", mode= "AppCursor" }, # Goto $
#   { key = "Back", mods = "Control", chars= "\u001b\u007f" }, # Delete word
#   { key = "Back", mods = "Control|Super", chars= "\u0015" }, # Delete line
# ]