import = [
  "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[shell]
program = "/bin/zsh"
args = ["-l"]

[font]
size = 12
offset ={ x= 0, y = -1 }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

[window]
dynamic_padding = true
decorations = "Full"
padding ={ x = 0, y = 0 }

[env]
TERM = "xterm-256color"
